globalExecGap: 10
settings:
  domainName: "lvmetabot.td82.ru"
#  bindProto: "https"
#  bindAddress: "::"
#  bindPort: 8443
#  keyFileName: "server-key.pem"
#  certFileName: "server-cert.pem"
  bindProto: "http"
  bindAddress: "::"
  bindPort: 8080
botTree:
  lvgitpullbot:
    botToken: '1042439418:AAHdW788KI38KCmrSo9P0AjIFWzmMpEO8lU'
    botUrl: '/lvgitpull'
    commands:
      git_pull:
        exec: "git pull"
        permissionChatIdMapping:
          155465626:
            - 155465626
          490767837:
            - 490767837
          -1001330975219:
            - 490767837
            - 155465626
      ls:
        exec: "ls"
        permissionChatIdMapping:
          155465626:
            - 155465626
          490767837:
            - 490767837
          -1001330975219:
            - 490767837
            - 155465626
  someanotherbot:
    botToken: 'unk'
    botUrl: '/someanother'
    commands:
      ls:
        exec: "ls"
        permissionChatIdMapping:
          155465626:
            - 155465626
          490767837:
            - 490767837
          -1001330975219:
            - 490767837
            - 155465626