globalExecGap: 10
settings:
  domainName: "lvmetabot.td82.ru"
#  bindProto: "https"
#  bindAddress: "::"
#  bindPort: 8443
#  keyFileName: "server-key.pem"
#  certFileName: "server-cert.pem"
  bindProto: "http"
  bindAddress: "::"
  bindPort: 8080
botTree:
  lvgitpullbot:
    botToken: '1042439418:AAHdW788KI38KCmrSo9P0AjIFWzmMpEO8lU'
    botUrl: '/lvgitpull'
    botChat: -1001330975219
    execGap: 10
  someanotherbot:
    botToken: 'unk'
    botUrl: '/someanother'
    botChat: -1001330975219