globalExecGap: 10
settings:
  domainName: "lvmetabot.td82.ru"
  keyFileName: "server-key.pem"
  certFileName: "server-cert.pem"
botTree:
  lvgitpullbot:
    botToken: '1017280662:AAHu5nNmBOilY2QuRDJws0kAtqMEDCDQqL8'
    botUrl: '/lvgitpull'
    botChat: -1001330975219
    execGap: 10
  someanotherbot:
    botToken: 'unk'
    botUrl: '/someanother'
    botChat: -1001330975219